version: "3.8"

services:

  fullnode:
    container_name: tron-fullnode
    build: .
    ports: 
      - 8080:8080
      - 8090:8090
      - 18888:18888
      - 50051:50051
    volumes:
      - tron-data:/data
      - ./mainnet.conf:/java-tron/mainnet.conf
      - ./testnet.conf:/java-tron/testnet.conf
    command: >
      -jvm "{-Xmx10g -Xms10g}" 
      -c /java-tron/mainnet.conf
      -d /data 
      -w 
    healthcheck:
      test: "curl --silent --fail -X GET  http://127.0.0.1:8091/walletsolidity/listwitnesses"

  client:
    container_name: tron-nodejs
    build: ./tron-nodejs
    volumes: 
      - ./tron-nodejs/client.js:/client.js
    depends_on:
      fullnode:
        condition: service_healthy
    environment: 
      - FULLNODE_URL=http://fullnode:8090
      - SOLIDITY_URL=http://fullnode:8091


  # client:
  #   container_name: tron-python
  #   build: ./tron-python 
  #   volumes: 
  #     - ./tron-python/client.py:/client.py
  #   depends_on:
  #     fullnode:
  #       condition: service_healthy
  #   environment: 
  #     - FULLNODE_URL=http://fullnode:8090
  #     - SOLIDITY_URL=http://fullnode:8091


volumes:
  tron-data: